config/routes.rb
SeatYourself::Application.routes.draw do
  
  resources :restaurants do
    resources :reservations, only: [:new,:create,:show,:index]
    resrouces :reviews
  end
    
  resources :users, :only => [:new, :create] 
   

  root 'home#index'

  

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :phone, :address, :presence => true

  has_many :users, through: :reservations
  has_many :reservations
  has_many :reveiws
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
  



  def new
     @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save 
      redirect_to root 
    else
      render :new
    end  
  end


  def index
    # @restaurants = Restaurant.all
  end

  def show
  end

  def edit
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :phone, :price_range, :address, :seats, :category, :neighbourhood)  
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def new
    if Rails.env.development?
      @restaurant = FactoryGirl.build(:restaurant_with_full_description)
    else
      @restaurant = Restaurant.new
     end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save 
      redirect_to @restaurant, notice: "Restaurant successfully added." 
    else
      render :new
    end  
  end


  def index
    @restaurants = Restaurant.all
  end

  def show
   load_restaurant
    @reservation = Reservation.new
  end

  def edit
    load_restaurant
  end

  def update
    load_restaurant
    if @restaurant.update_attributes(restaurant_params)
      redirect_to @restaurant, notice: "Successfully updated!"
    else
      render :new
    end  
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :phone, :price_range, :address, :seats, :category, :neighbourhood)  
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:id])    
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div id="restaurant_form">
  <%= form_for @restaurant do |f| %>


    <% if @restaurant.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2> 
      <ul>
        <%  @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div><br>
   
    <div class="field">
      <%= f.label :address %>
      <%= f.text_area :address %>
    </div><br>
   
    <div class="field">
      <%= f.label :neighbourhood %>
      <%= f.text_field :neighbourhood %>
    </div><br>
   
    <div class="field">
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div><br>
   
    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div><br>
   
    <div class="field">
      <%= f.label :price_range %>
      <%= f.text_field :price_range %>
    </div><br>
   
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div><br>
   
    <div class="field">
      <%= f.label :seats %>
      <%= f.number_field :seats %>
    </div><br>

    
    <div class="actions">
      <%= f.submit %>
    </div><br>


  </div>








   <% end %> 

app/views/restaurants/edit.html.erb
<h1>Edit Screen</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurant Listing</h1>


<% @restaurants.each do |restaurant| %>
  <div class="restaurant_display">
    <h2><%= link_to restaurant.name, restaurant %></h2>
    Category: <%= restaurant.category %> 
    Price Range: <%= restaurant.price_range %><br>
    <%= restaurant.address %><br>
    <%= restaurant.neighbourhood %><br>
    <%= restaurant.phone %><br>
    <p><%= restaurant.description %></p>
  </div>
  <br>
<% end %>

app/views/restaurants/new.html.erb
<h1>Restaurant#new</h1>
<p>Find me in app/views/restaurant/new.html.erb</p>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<%= link_to "Edit", edit_restaurant_path %>

<div class="restaurant_display">
<h1><%= @restaurant.name %></h1>
Category: <%= @restaurant.category %>
Price Range: <%= @restaurant.price_range %>
<br>
<%= @restaurant.address %><%= @restaurant.neighbourhood %>
<br>
<%= @restaurant.phone %>
<br>
<%= @restaurant.description %>
</div>

<%#= render 'reservations/form' %>


<%= link_to "Make a reservation", new_restaurant_reservation_path(restaurant_id: @restaurant.id) %>